# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a06450185741e9f50b72b95d69d85bc5c63fdef7905bf1b0353c72005f9842a72f8dbeff59cfe39590253022447ca8d85e9e6182fbe611faafd04d449e83ce3

test:
  secret_key_base: 616a18e16ec3ed710630dd3412482640a4609a81d22f990200047687a2b4ffbedd23234375641c3bf3e20eed84dd24e8ffe72f411950695ea1ac27ae2935d06a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
